# generated via: helm get manifest heapster
# NOTE: Created via a mixture of manually and with the aid of 'helm get manifest'
# E0105 00:41:05.012572       1 manager.go:101] Error in scraping containers from kubelet_summary:192.168.205.10:10250: request failed - "403 Forbidden", response: "Forbidden (user=system:serviceaccount:kube-system:heapster, verb=get, resource=nodes, subresource=stats)"
# E0105 00:41:05.016361       1 manager.go:101] Error in scraping containers from kubelet_summary:192.168.205.11:10250: request failed - "403 Forbidden", response: "Forbidden (user=system:serviceaccount:kube-system:heapster, verb=get, resource=nodes, subresource=stats)"
# E0105 00:41:05.077137       1 manager.go:101] Error in scraping containers from kubelet_summary:192.168.205.12:10250: request failed - "403 Forbidden", response: "Forbidden (user=system:serviceaccount:kube-system:heapster, verb=get, resource=nodes, subresource=stats)"
# W0105 00:41:25.061941       1 manager.go:152] Failed to get all responses in time (got 0/3)
# E0105 00:42:05.081610       1 manager.go:101] Error in scraping containers from kubelet_summary:192.168.205.12:10250: request failed - "403 Forbidden", response: "Forbidden (user=system:serviceaccount:kube-system:heapster, verb=get, resource=nodes, subresource=stats)"
# E0105 00:42:05.082859       1 manager.go:101] Error in scraping containers from kubelet_summary:192.168.205.10:10250: request failed - "403 Forbidden", response: "Forbidden (user=system:serviceaccount:kube-system:heapster, verb=get, resource=nodes, subresource=stats)"
# E0105 00:42:05.084330       1 manager.go:101] Error in scraping containers from kubelet_summary:192.168.205.11:10250: request failed - "403 Forbidden", response: "Forbidden (user=system:serviceaccount:kube-system:heapster, verb=get, resource=nodes, subresource=stats)"
# W0105 00:42:25.096540       1 manager.go:152] Failed to get all responses in time (got 0/3)
##################################################################
# kubectl get clusterroles system:heapster -o yaml
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: system:heapster
# rules:
# - apiGroups:
#   - ""
#   resources:
#   - events
#   - namespaces
#   - nodes
#   - pods
#   verbs:
#   - get
#   - list
#   - watch
# - apiGroups:
#   - extensions
#   resources:
#   - deployments
#   verbs:
#   - get
#   - list
#   - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: heapster
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  # - get
  # - list
  # - watch
  - '*'
- apiGroups:
  - "extensions"
  - "apps"
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  - nodes
  - nodes/stats
  - nodes/status
  - pods
  - pods/status
  verbs:
  # FIXME: can't figure it out for the moment, going for wildcard till then
  # - get
  - '*'
# - apiGroups:
#   - extensions
#   - apps
#   resources:
#   - deployments
#   verbs:
#   - get
#   - list
#   - watch
#   - update
#   - patch
# # "" indicates the core API group
# - apiGroups:
#   - ""
#   resources:
#   - events
#   - namespaces
#   - nodes
#   - pods
#   - deployments
#   verbs:
#   - get
#   - list
#   - update
#   - watch
# NOTE: DISABLED
# ---
# apiVersion: rbac.authorization.k8s.io/v1beta1
# kind: ClusterRoleBinding
# metadata:
#   name: heapster
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: heapster
# subjects:
# - kind: ServiceAccount
#   name: heapster
#   namespace: kube-system
---
# Source: heapster/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: heapster
  namespace: kube-system
  labels:
    app: heapster
    chart: heapster-0.3.2
    heritage: Tiller
    release: heapster
    kubernetes.io/cluster-service: "true"
---
# FIXME: kubectl create serviceaccount heapster --namespace=kube-system
# FIXME: kubectl create clusterrolebinding heapster-role --clusterrole=system:heapster --serviceaccount=kube-system:heapster --namespace=heapster
# Source: heapster/templates/heapster-crb.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: heapster
  labels:
    app: heapster
    chart: heapster-0.3.2
    heritage: Tiller
    release: heapster
    kubernetes.io/cluster-service: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:heapster
subjects:
  - kind: ServiceAccount
    name: heapster
    namespace: kube-system
---
# Source: heapster/templates/pod-nanny-role.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: heapster-pod-nanny
  namespace: kube-system
  labels:
    app: heapster
    chart: heapster-0.3.2
    heritage: Tiller
    release: heapster
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - nodes/stats
  - namespaces
  verbs:
  - get
  - list
  - watch
  - create
- apiGroups:
  - "extensions"
  - "apps"
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
# - apiGroups:
#   - ""
#   resources:
#   - nodes/stats
#   verbs:
#   - get
#   - list
#   - watch
---
# Source: heapster/templates/pod-nanny-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: heapster-pod-nanny
  namespace: kube-system
  labels:
    app: heapster
    chart: heapster-0.3.2
    heritage: Tiller
    release: heapster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: heapster-pod-nanny
subjects:
- kind: ServiceAccount
  name: heapster
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: heapster
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: heapster-pod-nanny
subjects:
- kind: ServiceAccount
  name: heapster
  namespace: kube-system
---
# Source: heapster/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: heapster
  namespace: kube-system
  labels:
    kubernetes.io/name: Heapster
    chart: "heapster-0.3.2"
    app: heapster
    heritage: "Tiller"
    release: "heapster"
spec:
  type: ClusterIP
  ports:
  # - port: 80
  - port: 8082
    targetPort: 8082
    protocol: TCP
  selector:
    app: heapster
---
# Source: heapster/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heapster
  namespace: kube-system
  annotations:
    {}

  labels:
    chart: "heapster-0.3.2"
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        {}

      labels:
        app: heapster
        k8s-app: heapster
    spec:
      serviceAccountName: heapster
      containers:
      - name: heapster
        image: "k8s.gcr.io/heapster:v1.5.2"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8082
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8082
          initialDelaySeconds: 180
          timeoutSeconds: 5
        resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi

        command:
          - "/heapster"
          # - "--source=kubernetes.summary_api:''"
          - "--source=kubernetes.summary_api:https://kubernetes.default:443?useServiceAccount=true&kubeletHttps=true&kubeletPort=10250&insecure=true"
          # - "--sink=log"
          # - "--vmodule=*=2"
          # - "--api-server"
          # - "--sink=influxdb:http://monitoring-influxdb.kube-system.svc:8086"

      - name: heapster-nanny

        image: "k8s.gcr.io/addon-resizer:1.7"
        imagePullPolicy: IfNotPresent
        resources:
            limits:
              cpu: 50m
              memory: 90Mi
            requests:
              cpu: 50m
              memory: 90Mi

        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        command:
          - "/pod_nanny"
          - "--deployment=heapster"
          - "--container=heapster"
          - "--cpu=150m"
          - "--extra-cpu=10m"
          - "--memory=200Mi"
          - "--extra-memory=6Mi"
          - "--threshold=5"
          - "--poll-period=300000"
