# https://gist.github.com/gnarf/b103e77f37236ca72d8e
# SOURCE: \cat roles/*/vagrant-config.yml | pbcopy
:vms:
  borg-queen-01:
    :hostname: "borg-queen-01"
    :name: "borg-queen-01"
    :type: "master"
    :box: "ubuntu/xenial64"
    :eth1: "192.168.205.10"
    :ip: "192.168.205.10"
    :mem: 2048
    :ram: 2048
    :cpu: 2
    :id: 10

  borg-worker-01:
    :hostname: "borg-worker-01"
    :name: "borg-worker-01"
    :type: "node"
    :box: "ubuntu/xenial64"
    :eth1: "192.168.205.11"
    :ip: "192.168.205.11"
    :mem: 5048
    :ram: 5048
    :cpu: 4
    :id: 10

  borg-worker-02:
    :hostname: "borg-worker-02"
    :name: "borg-worker-02"
    :type: "node"
    :box: "ubuntu/xenial64"
    :eth1: "192.168.205.12"
    :ip: "192.168.205.12"
    :mem: 5048
    :ram: 5048
    :cpu: 4
    :id: 10
