# https://gist.github.com/gnarf/b103e77f37236ca72d8e
# SOURCE: \cat roles/*/vagrant-config.yml | pbcopy
:servers:
  k8s-head:
    :name: "k8s-head"
    :type: 'master'
    :box: 'ubuntu/xenial64'
    # :box_version => "20180831.0.0"
    :eth1: '192.168.205.10'
    :mem: '2048'
    :cpu: '2'
  k8s-node-1:
    :name: 'k8s-node-1'
    :type: 'node'
    :box: 'ubuntu/xenial64'
    # :box_version => "20180831.0.0"
    :eth1: '192.168.205.11'
    :mem: '2048'
    :cpu: '2'

  k8s-node-2:
    :name: 'k8s-node-2'
    :type: 'node'
    :box: 'ubuntu/xenial64'
    # :box_version => "20180831.0.0"
    :eth1: '192.168.205.12'
    :mem: '2048'
    :cpu: '2'
