---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-pvc
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: prometheus-operator
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "nfs-dynamic-class"
  resources:
    requests:
      storage: "2Gi"


---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-adapter-tmpfs-pvc
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: prometheus-operator
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "nfs-dynamic-class"
  resources:
    requests:
      storage: "2Gi"


---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-adapter-volume-serving-cert-pvc
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: prometheus-operator
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "nfs-dynamic-class"
  resources:
    requests:
      storage: "2Gi"
