apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  labels:
    run: nginx
spec:
  ports:
  - name: http
    port: 3000
    targetPort: http
  selector:
    app: grafana
    run: nginx
