---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd-es
  namespace: kube-system
  labels:
    k8s-app: fluentd-es
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    boss-part-of: efk
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd-es
  # namespace: kube-system
  labels:
    k8s-app: fluentd-es
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    boss-part-of: efk
rules:
- apiGroups:
  - ""
  resources:
  - "namespaces"
  - "pods"
  verbs:
  - "get"
  - "watch"
  - "list"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd-es
  # FIXME: DON'T WE NEED THIS?? # namespace: kube-system ( Answer is, no we dont )
  labels:
    k8s-app: fluentd-es
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    boss-part-of: efk
roleRef:
  kind: ClusterRole
  name: fluentd-es
  # FIXME: https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/fluentd-daemonset-elasticsearch-rbac.yaml
  # DISABLED: temporary # apiGroup: ""
  # apiGroup: rbac.authorization.k8s.io
  apiGroup: ""
subjects:
- kind: ServiceAccount
  name: fluentd-es
  namespace: kube-system
  # FIXME: https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/fluentd-daemonset-elasticsearch-rbac.yaml
  apiGroup: ""
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-es-v2.2.1
  namespace: kube-system
  labels:
    k8s-app: fluentd-es
    version: v2.2.1
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    boss-part-of: efk
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-es
      version: v2.2.1
  template:
    metadata:
      labels:
        k8s-app: fluentd-es
        kubernetes.io/cluster-service: "true"
        version: v2.2.1
        boss-part-of: efk
      # This annotation ensures that fluentd does not get evicted if the node
      # supports critical pod annotation based priority scheme.
      # Note that this does not guarantee admission on the nodes (#40573).
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        seccomp.security.alpha.kubernetes.io/pod: 'docker/default'
    spec:
      priorityClassName: system-node-critical
      # serviceAccount: fluentd-es
      serviceAccountName: fluentd-es
      containers:
      - name: fluentd-es
        # image: image: k8s.gcr.io/fluentd-elasticsearch:v2.2.0
        # SOURCE: https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/fluentd-es-image/Dockerfile
        # image: gcr.io/google-containers/fluentd-elasticsearch:v2.2.1
        image: k8s.gcr.io/fluentd-elasticsearch:v2.2.0
        # FIXME: Try using this guy instead
        # SOURCE: https://github.com/fluent/fluentd-kubernetes-daemonset/tree/master/docker-image/v1.3/debian-elasticsearch
        # image: fluent/fluentd-kubernetes-daemonset:elasticsearch
        env:
          - name: FLUENTD_ARGS
            value: --no-supervisor -q
          # - name:  FLUENT_ELASTICSEARCH_HOST
          #   value: "elasticsearch-logging"
          # - name:  FLUENT_ELASTICSEARCH_PORT
          #   value: "9200"
          # - name: FLUENT_ELASTICSEARCH_SCHEME
          #   value: "http"
          # # X-Pack Authentication
          # # =====================
          # - name: FLUENT_ELASTICSEARCH_USER
          #   value: "elastic"
          # - name: FLUENT_ELASTICSEARCH_PASSWORD
          #   value: "changeme"
        resources:
          limits:
            memory: 500Mi
            # memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: libsystemddir
          mountPath: /host/lib
          readOnly: true
        - name: config-volume
          mountPath: /etc/fluent/config.d
      nodeSelector:
        beta.kubernetes.io/fluentd-ds-ready: "true"
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      # It is needed to copy systemd library to decompress journals
      - name: libsystemddir
        hostPath:
          path: /usr/lib64
      - name: config-volume
        configMap:
          # name: fluentd-es-config-v0.1.0
          name: fluentd-es-config-v0.1.6
