source 'https://rubygems.org'

gem 'fluentd', '<=1.2.4'
gem 'activesupport', '~>5.2.1'
gem 'fluent-plugin-concat', '~>2.3.0'
gem 'fluent-plugin-detect-exceptions', '~>0.0.11'
gem 'fluent-plugin-elasticsearch', '~>2.11.5'
gem 'fluent-plugin-kubernetes_metadata_filter', '~>2.0.0'
gem 'fluent-plugin-multi-format-parser', '~>1.0.0'
gem 'fluent-plugin-prometheus', '~>1.0.1'
gem 'fluent-plugin-systemd', '~>1.0.1'
gem 'fluent-plugin-concat'
gem 'oj', '~>3.6.5'

# https://github.com/viaq/fluent-plugin-audit_log_parser
# https://github.com/shivaken/fluent-plugin-better-timestamp
# https://github.com/spynode/fluent-plugin-better-timestamp
# https://bitbucket.org/winebarrel/fluent-plugin-buffered-filter
# https://github.com/bwalex/fluent-plugin-docker-format
# https://github.com/okushchenko/fluent-plugin-docker-journald-concat
# https://github.com/fabric8io/fluent-plugin-docker_metadata_filter
# https://github.com/libresh/fluent-plugin-haproxy
# https://github.com/bungoume/fluent-plugin-ignore-filter
# https://github.com/One-com/fluent-plugin-journal-parser
# https://github.com/repeatedly/fluent-plugin-multi-format-parser
# https://github.com/activeshadow/fluent-plugin-split-event
# https://github.com/lingochamp/fluent-plugin-statsd
# https://github.com/mamewotoko/fluent-plugin-ufw
# https://github.com/tagomoris/fluent-plugin-growthforecast
# https://github.com/studio3104/fluent-plugin-graphite
# https://github.com/gumi/fluent-plugin-mysql-status
# https://github.com/robertpitt/fluent-plugin-nginx-status
# https://github.com/enukane/fluent-plugin-pcapng
# https://github.com/tagomoris/fluent-plugin-ping-message
# https://github.com/fakechris/fluent-plugin-statsd
# https://github.com/sowawa/fluent-plugin-slack
# https://github.com/fangli/fluent-plugin-influxdb
# https://github.com/fluent/fluent-plugin-mongo
# https://github.com/tagomoris/fluent-plugin-mysql
