# SOURCE: https://github.com/kubernetes-incubator/metrics-server/tree/master/deploy/1.8%2B
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-server
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: metrics-server
  namespace: kube-system
  labels:
    k8s-app: metrics-server
spec:
  selector:
    matchLabels:
      k8s-app: metrics-server
  template:
    metadata:
      name: metrics-server
      labels:
        k8s-app: metrics-server
    spec:
      serviceAccountName: metrics-server
      volumes:
      # # mount in tmp so we can safely use from-scratch images and/or read-only containers
      # - name: tmp-dir
      #   emptyDir: {}
      # NFS4 version
      # - emptyDir: {}
      #   name: grafana-storage
      - name: tmp-dir
        persistentVolumeClaim:
          claimName: tmp-dir-pvc

      containers:
      - name: metrics-server
        image: k8s.gcr.io/metrics-server-amd64:v0.3.1
        imagePullPolicy: Always
        volumeMounts:
        - name: tmp-dir
          mountPath: /tmp

