---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tmp-dir-pvc
  namespace: "kube-system"
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "nfs-dynamic-class"
  resources:
    requests:
      storage: "1Gi"
