---
##############################################################################
# SERVERS: Install and configure rsyslogd
##############################################################################
- hosts: servers
  name: install tools on all servers
  gather_facts: True
  strategy: free
  become: yes
  become_method: sudo
  environment:
    DEBIAN_FRONTEND: noninteractive
  roles:
    - role: boss-ansible-role-tools
      task: tools
      timezone: 'America/New_York'
      bossjones__user: vagrant
      bossjones__group: vagrant
      boss__tools__install_docker_tools: True
      boss__tools__install_kube_tools: True
      boss__tools__install_rust_tools: False
      tags:
        - boss-ansible-role-tools
    - role: boss-ansible-role-tools
      task: kube
      timezone: 'America/New_York'
      bossjones__user: vagrant
      bossjones__group: vagrant
      boss__tools__install_docker_tools: True
      boss__tools__install_kube_tools: True
      boss__tools__install_rust_tools: False
      tags:
        - boss-ansible-role-tools
    - role: boss-ansible-role-tools
      task: docker
      timezone: 'America/New_York'
      bossjones__user: vagrant
      bossjones__group: vagrant
      boss__tools__install_docker_tools: True
      boss__tools__install_kube_tools: True
      boss__tools__install_rust_tools: False
      tags:
        - boss-ansible-role-tools
    - role: boss-ansible-role-tools
      task: glances
      timezone: 'America/New_York'
      bossjones__user: vagrant
      bossjones__group: vagrant
      boss__tools__install_docker_tools: True
      boss__tools__install_kube_tools: True
      boss__tools__install_rust_tools: False
      tags:
        - boss-ansible-role-tools
    - role: boss-ansible-role-tools
      task: rust
      timezone: 'America/New_York'
      bossjones__user: vagrant
      bossjones__group: vagrant
      boss__tools__install_docker_tools: True
      boss__tools__install_kube_tools: True
      boss__tools__install_rust_tools: False
      tags:
        - boss-ansible-role-tools
    - role: boss-ansible-role-tools
      task: npm
      timezone: 'America/New_York'
      bossjones__user: vagrant
      bossjones__group: vagrant
      boss__tools__install_docker_tools: True
      boss__tools__install_kube_tools: True
      boss__tools__install_rust_tools: False
      tags:
        - boss-ansible-role-tools
