---
##############################################################################
# SERVERS: Install and configure rsyslogd
##############################################################################
- hosts: servers
  name: install tools on all servers
  gather_facts: True
  become: yes
  become_method: sudo
  vars:
    bossjones__user: vagrant
    bossjones__group: vagrant
    timezone: 'America/New_York'
  environment:
    DEBIAN_FRONTEND: noninteractive
  roles:
    - role: boss-ansible-role-tools
      task: tools
      bossjones__user: vagrant
      bossjones__group: vagrant
      boss__tools__install_docker_tools: True
      boss__tools__install_kube_tools: True
      boss__tools__install_rust_tools: True
      tags:
        - boss-ansible-role-tools
